---
deployment:
  tasks:
    - export DEPLOYPATH=/home/shreexco/public_html/
    - /bin/rm -rf $DEPLOYPATH/* 
    - /bin/rm -rf $DEPLOYPATH/.*
    - /bin/cp -rf dist/ $DEPLOYPATH/   # ← Change * to / (copies the whole dist folder)
    - /bin/mv $DEPLOYPATH/dist/* $DEPLOYPATH/   # Move contents up one level
    - /bin/rm -rf $DEPLOYPATH/dist   # Clean up the empty dist folder