---
deployment:
  tasks:
    - export DEPLOYPATH=/home/shreexco/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH/
    - echo "Deployment complete! Files copied to $DEPLOYPATH"